
#下面的配置只是示例，没有任何作用
# 对所有的服务该配置都生效
ribbon:
  #请求连接的超时时间
  ConnectTimeout: 5000
  #请求处理/响应的超时时间
  ReadTimeout: 5000
  #对所有操作请求都进行重试
  OkToRetryOnAllOperations: false
  #切换实例的重试次数
  MaxAutoRetriesNextServer: 0
  #当前实例的重试次数
  MaxAutoRetries: 0

  retryableStatusCodes: ''


#只针对  sevice-x生效
sevice-x:
  ribbon:
    ConnectTimeout: 1000
    ReadTimeout: 1000
    OkToRetryOnAllOperations: false
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1
    retryableStatusCodes: ''


