
#下面的配置只是示例，没有任何作用
# 对所有的服务该配置都生效
ribbon:
  #请求连接的超时时间
  ConnectTimeout: 5000
  #请求处理/响应的超时时间
  ReadTimeout: 5000
  #对所有操作请求都进行重试  默认在get请求下会重试，其他情况不会重试
  OkToRetryOnAllOperations: false
  #切换实例的重试次数  要重试的下一个服务器的最大数量（不包括第一个服务器）
  MaxAutoRetriesNextServer: 0
  #当前实例的重试次数 同一服务器上的最大重试次数（不包括首次尝试）
  MaxAutoRetries: 0

  retryableStatusCodes: ''
  # retryableStatusCodes属性(此参数可在配置文件中配置’ribbon.retryableStatusCodes’或’service-x.ribbon.retryableStatusCodes’，默认值是空字符串，多值http status时可用逗号隔开)，这个属性是表示http状态行在这些指定范围内就可重试



#只针对  sevice-x生效
sevice-x:
  ribbon:
    ConnectTimeout: 1000
    ReadTimeout: 1000
    OkToRetryOnAllOperations: false
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1
    retryableStatusCodes: ''


