# com.mysql.jdbc.Driver 是 mysql-connector-java 5中的，
# com.mysql.cj.jdbc.Driver 是 mysql-connector-java 6以及以上中的

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/powernode
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  #目的是为了省略resultType里的代码量
  type-aliases-package: com.chf.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl