
# feign 开启 hystrix  false的话，执行方法调用的时候走FeignInvocationHandler 。  true的话 走 HystrixInvocationHandler
# Feign是自带Hystrix熔断器的，不过在D版本之后，熔断器默认是关闭的，需要通过如下配置进行开启。
# Feign支持通过配置的方式，开启请求和返回的GZIP压缩，减少请求的网络消耗
feign:
  hystrix:
    enabled: false
#  client:
#    config:
#      default:
#        logger-level: full   #最高级别日志   低到高none basic  headers full  建议使用null和basic模式、调试可以开启full模式。


hystrix:
  command:
    ## 全局默认配置
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 12000  # 该配置需要比ribbon超时时间长

    ## 单独设置
    hystrix-feing-client:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

#      fallback:
#        enabled: false

#      circuitBreaker:
#        enabled: false

  threadpool:
    default:
      coreSize: 50
      maxQueueSize: 50
      queueSizeRejectionThreshold: 25


# 对所有的服务该配置都生效
ribbon:
  #请求连接的超时时间
  ConnectTimeout: 5000
  #请求处理/响应的超时时间
  ReadTimeout: 1000
  #对所有操作请求都进行重试  默认在get请求下会重试，其他情况不会重试
  OkToRetryOnAllOperations: false
  #切换实例的重试次数  要重试的下一个服务器的最大数量（不包括第一个服务器）
  MaxAutoRetriesNextServer: 0
  #当前实例的重试次数 同一服务器上的最大重试次数（不包括首次尝试）
  MaxAutoRetries: 0

# 针对重试次数不生效问题是这样的，刚开始我认为的MaxAutoRetries和MaxAutoRetriesNextServer都配置为1，重试次数为1次，一共请求2次。
#
#其实当MaxAutoRetriesNextServer为1时，请求超时或失败后不论有几个实例都会切换一次，也就是说即使只有1个实例，也会切换到自己，然后再去请求，所以就出现了重试次数为3次的现象（第一次超时重试+切换实例请求+切换实例超时重试）。
#
#所以Ribbon请求最多会被执行(1 + maxAutoRetries ) * (1 + MaxAutoRetriesNextServer)次。


#  https://www.cnblogs.com/wangerdan/articles/17859211.html