http:
  maxTotal: 100         #最大连接数
  defaultMaxPerRoute: 20  #并发数
  connectTimeout: 1000   #创建连接的最长时间
  connectionRequestTimeout: 500  #从连接池中获取到连接的最长时间
  socketTimeout: 10000 #数据传输的最长时间
  staleConnectionCheckEnabled: true  #提交请求前测试连接是否可用
  validateAfterInactivity: 3000000   #可用空闲连接过期时间,重用空闲连接时会先检查是否空闲时间超过这个时间，如果超过，释放socket重新建立




# http工具配置
okhttp:
  connect-timeout: 5 #socket连接超时时间（秒）
  read-timeout: 5
  write-timeout: 5
  max-idle-connections: 10 #最大空闲连接数
  keep-alive-duration: 300 #空闲连接最多存活时间（秒）



my:
  thread:
    coreSize: 1
    maxSize: 1
    keepAliveTime: 1